export const datas = [
  {
    id: 1,
    name: "Áo sơ mi, siêu sạch siêu ngon. Đặc biệt không bán!!",
    desc: "Sau cơn mưa thì trời lại sáng ",
    price: "480.000đ",
    img: "./asset/img/Do1.jpg",
  },
  {
    id: 2,
    name: "Đồ ngủ có hòi con vinh đến từ Chợ Đồng Xuân",
    desc: "Có không giữ mất thì mua cái mới",
    price: "167.000đ",
    img: "./asset/img/Thao1.jpg",
  },
  {
    id: 3,
    name: "Quần phông và áo jean",
    desc: "Toán rời rạc: Ứng dụng trong Tin Học",
    price: "280.000đ",
    img: "./asset/img/Tram.jpg",
  },
  {
    id: 4,
    name: "Combo áo jead, nón bảo hiểm. Outfit đỉnh cao năm 2017",
    desc: "Trong màn đêm anh là ninja kiếm anh không có ra",
    price: "1480.000đ",
    img: "./asset/img/Do2.jpg",
  },
  {
    id: 5,
    name: "Áo khoác chống nóng mùa đông",
    desc: "Em của ngày xưa giờ là khác rồi",
    price: "320.000đ",
    img: "./asset/img/Thao3.jpg",
  },
  {
    id: 6,
    name: " Mua nhanh đi, hết sale đừng có khóc à",
    desc: "Người lái đò sông đà",
    price: "210.000đ",
    img: "./asset/img/Mai.jpg",
  },
  {
    id: 7,
    name: "Áo sơ mi, siêu sạch siêu ngon. Đặc biệt không bán!!",
    desc: "Cô gái đến từ hôm qua",
    price: "290.000đ",
    img: "./asset/img/Tram2.jpg",
  },
  {
    id: 8,
    name: "Combo áo sơ cụt tay + quần jean, duy nhất mỗi hôm",
    desc: "Nắng chiều lồng lộng giữa trời mưa",
    price: "720.000đ",
    img: "./asset/img/Thao2.jpg",
  },
  {
    id: 9,
    name: "Áo sơ mi, siêu sạch siêu ngon. Đặc biệt không bán!!",
    desc: "Lên chùa bẻ 1 cành sen",
    price: "290.000đ",
    img: "./asset/img/Tram2.jpg",
  },
  {
    id: 10,
    name: "Combo áo sơ cụt tay + quần jean, duy nhất mỗi hôm",
    desc: "Quá đủ cho 1 ngày rồi ",
    price: "720.000đ",
    img: "./asset/img/Thao2.jpg",
  },
];
